### Create a New User
POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"

}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"

}

### Who am i
GET http://localhost:3000/auth/whoami HTTP/1.1

### Sign Out
POST http://localhost:3000/auth/signout HTTP/1.1

### Find a Particular Users
GET http://localhost:3000/auth/3


### Find All The Users
GET http://localhost:3000/auth?email=amsdin@ss.com

### Delete a User with a Givin ID
DELETE http://localhost:3000/auth/4


### Update a User
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "amsdin@ss.com"
}

